### ISSUE TITLE
Linting and Formatting with Ruff

### ISSUE THREAD

**Issue by smaarmstrong** [smaarmstrong/lexiweb#1]
### Issue: Linting and Formatting with Ruff

**Description:**  
I want to streamline the linting and formatting process by using only Ruff for both tasks. The goal is to avoid fancy configurations while maintaining essential checks for whitespace, merge conflicts, and Python-specific linting and formatting issues. This should be reflected in the pre-commit hooks, GitHub Actions workflows, and the `.git/hooks/pre-commit` file to block commits when violations are found.

#### **1. Install Pre-commit**

To use pre-commit hooks, you need to install the `pre-commit` package. Run the following command:

```bash
pip install pre-commit
```

Then, install the hooks by running:

```bash
pre-commit install
```

This will set up the hooks from `.pre-commit-config.yaml` to run automatically on each commit.

#### **2. Install Ruff**

Ruff is a fast Python linter and formatter. To install it, run:

```bash
pip install ruff
```

This ensures that Ruff is available to run both in your pre-commit hooks and in your CI pipeline.

#### **3. Create Virtual Environment (Optional but Recommended)**

Create and activate a virtual environment to isolate dependencies:

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

Make sure your virtual environment is activated when you are running the commands for linting, formatting, and testing.

---

#### **1. `.pre-commit-config.yaml`:**

This configuration file ensures that `ruff` and basic hooks like removing trailing whitespace and fixing end-of-file issues are run before committing.

```yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.51.0  # Use the latest stable version
    hooks:
      - id: ruff
        args: ["--select", "F,E,W,C"]  # Customize linting rules as needed

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
```

1. Run `pre-commit install` to activate these hooks in your local environment.
2. To run the pre-commit checks manually on all files, use:

```bash
pre-commit run --all-files
```

---

#### **2. `.github/workflows/ci.yml`:**

This file sets up a GitHub Actions workflow that uses `ruff` to check code during pushes and pull requests. This is crucial for ensuring code quality before merging into the main branch.

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Specify the Python versions to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install ruff

      - name: Run ruff
        run: |
          source venv/bin/activate
          ruff . --select F,E,W,C  # Customize linting rules as needed

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
```

---

#### **3. `.git/hooks/pre-commit`:**

This file is a local Git hook that runs Ruff checks before every commit. It prevents commits from going through if there are any linting or formatting issues. This file won’t be tracked in version control, but you can set it up locally.

1. Create the `.git/hooks/pre-commit` file in your local repository and make it executable:

```bash
touch .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
```

2. Add the following content to the file:

```bash
#!/bin/bash

# Activate the virtual environment if needed
if [ -f "venv/bin/activate" ]; then
  source venv/bin/activate
fi

# Run Ruff to check for linting and formatting errors
echo "Running Ruff (linting and formatting)..."

# Check for linting violations
ruff_output=$(ruff . --select F,E,W,C)
if [ $? -ne 0 ]; then
  echo "Ruff found linting violations:"
  echo "$ruff_output"
  exit 1  # Block the commit
else
  echo "Ruff linting passed!"
fi

# Check for formatting violations
ruff_format_output=$(ruff . --diff)
if [ $? -ne 0 ]; then
  echo "Ruff found formatting issues:"
  echo "$ruff_format_output"
  exit 1  # Block the commit
else
  echo "Ruff formatting passed!"
fi

echo "All checks passed. Proceeding with commit."
```

3. The hook will now run automatically on every commit and block the commit if any issues are detected.

---

### Objective:

The goal is to streamline the development process by using Ruff exclusively for linting and formatting in pre-commit hooks and GitHub Actions, while keeping configurations minimal. Additionally, a local `.git/hooks/pre-commit` file should block any commits that fail Ruff’s checks.
